#!/usr/bin/env bash
# Register org-protocol as the org-protocol handler in mimeapps.list
MIMEAPPS_PATH=~/.local/share/applications/mimeapps.list
HANDLER='x-scheme-handler/org-protocol'
EXPRESSION='x-scheme-handler/org-protocol=org-protocol.desktop'
TEMPFILE=/tmp/orgprotocol_handler
case $(grep ${HANDLER} ${MIMEAPPS_PATH} >${TEMPFILE}; echo $?) in 
    0)
        # found
        echo "Skipping: a handler for org-protocol was already installed in ${MIMEAPPS_PATH}: '$(cat ${TEMPFILE})'"
        ;;
    1)
        # not found
        echo "Installing nixnote_url as the org-protocol uri handler in ${MIMEAPPS_PATH}"
        echo ${EXPRESSION} >> ${MIMEAPPS_PATH}
        ;;
    *)
        # an error occurred
        echo "Error installing nixnote_url as the org-protocol uri handler in ${MIMEAPPS_PATH}"
        ;;
esac
rm -f ${TEMPFILE}
