#!/usr/bin/env bash
source ${BASH_SOURCE%/*}/_require_sudo.sh
require_sudo

apt install -y \
    direnv \
    docker.io \
    flatpak \
    fonts-open-sans \
    fonts-powerline \
    fzf \
    graphviz \
    guake \
    hexchat \
    htop \
    iftop \
    meld \
    nautilus-admin \
    pandoc \
    pdftk \
    pinta \
    plantuml \
    postgresql-client-common \
    python3-dev \
    python3-venv \
    pipx \
    ripgrep \
    shellcheck \
    sqlite3 \
    sqlitebrowser \
    stow \
    texlive \
        texlive-plain-generic \
        texlive-science \
        dvipng \
        texlive-latex-extra \
    tmux \
    traceroute \
    ttf-mscorefonts-installer \
    universal-ctags \
    vim-gtk3 \
    webp \
    wireshark \
    xclip \
    xmlcopyeditor \
    xmlstarlet
