---
- name: Stow configuration files
  stow:
    state: present
    package: "{{ item }}"
    dir: roles/dbg/stow
  with_items:
    - maven
    - mount-z-drive

- name: Configure DBG proxy for snap
  command: "{{ item }}"
  with_items:
    - 'snap set system proxy.http="http://webproxy.deutsche-boerse.de:8080"'
    - 'snap set system proxy.https="http://webproxy.deutsche-boerse.de:8080"'
  become: true
