---
- name: Stow configuration files
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/dbg/stow
  with_items:
    - maven
    - mount-z-drive

- name: Configure DBG proxy in git
  blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    create: true
    block: |
      host github.com
        hostname ssh.github.com
        user git
        port 443
        proxycommand socat - PROXY:webproxy.deutsche-boerse.de:%h:%p,proxyport=8080

      host gitlab.com
        hostname altssh.gitlab.com
        user git
        port 443
        proxycommand socat - PROXY:webproxy.deutsche-boerse.de:%h:%p,proxyport=8080
