---
- name: Stow Tmux configuration files
  stow:
    state: present
    package: tmux
    dir: roles/tmux/stow

- name: Install Tmux Plugin Manager
  git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Install Tmux Plugins
  shell: tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins
