---
- name: Install core libraries using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - direnv
    - docker.io
    - fzf
    - htop
    - iftop
    - pandoc
    - pdftk
    - postgresql-client-common
    - python3-dev
    - python3-venv
    - pipx
    - ripgrep
    - shellcheck
    - sqlite3
    - stow
    - tmux
    - tree
    - traceroute
    - universal-ctags

- name: Stow configuration files
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/files 
  with_items:
    - stow
    - tmux
    - gitconfig
    - bashrc
    - vim

- name: Install Vundle
  git:
    repo: git@github.com:VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Install Vim plugins
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  register: result
  failed_when: ( result.rc not in [0,1] )   # it returns a 1 even when successful
