---
- name: Install core libraries using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - direnv
    - docker.io
    - fzf
    - htop
    - iftop
    - pandoc
    - pdftk
    - postgresql-client-common
    - python3-dev
    - python3-venv
    - pipx
    - ripgrep
    - shellcheck
    - sqlite3
    - stow
    - tmux
    - tree
    - traceroute
    - universal-ctags
    - vim

- name: Stow configuration files
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/stow
  with_items:
    - stow
    - gitconfig
    - tmux

- name: Stow configuration files with no folding
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/stow
  with_items:
    - bashrc

- name: Install Tmux Plugin Manager
  git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: Install Tmux Plugins
  shell: tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins
