---
- name: Create cache directory for this Playbook
  file:
    path: "{{ ansible_env.HOME }}/.cache/dotfiles"
    state: directory

- name: Install core libraries using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - direnv
    - docker.io
    - fzf
    - htop
    - iftop
    - pandoc
    - pdftk
    - postgresql-client-common
    - python3-dev
    - python3-venv
    - pipx
    - ripgrep
    - shellcheck
    - sqlite3
    - stow
    - tmux
    - tree
    - traceroute
    - universal-ctags
    - vim

- name: Install pipx applications
  command:
    cmd: "pipx install {{ item }}"
    creates: "~/.local/pipx/venvs/{{ item }}"
  with_items:
    - docker-compose
    - poetry

- name: Stow configuration files
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/stow
  with_items:
    - stow
    - gitconfig
    - tmux

- name: Stow configuration files with no folding
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/stow
    no-folding: yes
  with_items:
    - bashrc

- name: Make .profile read .profile.d
  blockinfile:
    path: ~/.profile
    block: |
      # Read extra configuration from ~/.profile.d
      if [ -d "$HOME"/.profile.d ]; then
        for file in "$HOME"/.profile.d/*.profile; do
            [ -f "$file" ] && . "$file"
        done
      fi

- name: Install Poetry bash completions
  shell:
    cmd: "poetry completions bash > ~/.local/share/bash-completion/completions/poetry.bash-completion"
    creates: "~/.local/share/bash-completion/completions/poetry.bash-completion"

- name: Install Tmux Plugin Manager
  git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Install Tmux Plugins
  shell: tmux source ~/.tmux.conf && ~/.tmux/plugins/tpm/bin/install_plugins
