---
- name: Install core libraries using APT
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - direnv
    - docker.io
    - fzf
    - htop
    - iftop
    - pandoc
    - pdftk
    - postgresql-client-common
    - python3-dev
    - python3-venv
    - pipx
    - ripgrep
    - shellcheck
    - sqlite3
    - stow
    - tmux
    - traceroute
    - universal-ctags

- name: Stow configuration files
  stow:
    state: present
    package: '{{ item }}'
    dir: roles/common/files 
  with_items:
    - stow
    - tmux
    - gitconfig
    - bashrc
    - vim
