#!/usr/bin/env bash
# Manual install scripts for the setup of a new machine.
#
# These probably won't run by just sourcing and calling the functions. Next time
# I'll fully automate it, if it makes sense. For now it's just a reference.

install_sdkman() {
	curl -s "https://get.sdkman.io" | bash
}

install_pyenv() {
	sudo apt install -y \
		build-essential libssl-dev zlib1g-dev \
		libbz2-dev libreadline-dev libsqlite3-dev \
		wget curl llvm libncurses5-dev libncursesw5-dev \ 
		xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
	curl https://pyenv.run | bash
}

install_pipx() {
    pip install pipx
}

install_docker-compose() {
    pipx install docker-compose
}

install_nix() {
    # See documentation in https://nixos.org/manual/nix/stable/#chap-quick-start
    sh <(curl -L https://nixos.org/nix/install) --daemon
}
install_node() {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
    source .bashrc
    nvm install node
}

install_joplin() {
    # Install AppImage taking care of app logo
    wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
}

install_poetry() {
    pipx install poetry
    poetry completions bash > ~/.local/share/bash-completion/completions/poetry.bash-completion
}


